export const FETCHING_ALL_CHECKLIST_REQUEST =
  'checklist/FETCHING_ALL_CHECKLIST_REQUEST';
export const FETCHING_ALL_CHECKLIST_FAILURE =
  'checklist/FETCHING_ALL_CHECKLIST_FAILURE';
export const FETCHING_ALL_CHECKLIST_SUCCESS =
  'checklist/FETCHING_ALL_CHECKLIST_SUCCESS';

export const SAVE_CHECKLIST_REQUEST = 'checklist/SAVE_CHECKLIST_REQUEST';
export const SAVE_CHECKLIST_FAILURE = 'checklist/SAVE_CHECKLIST_FAILURE';
export const SAVE_CHECKLIST_SUCCESS = 'checklist/SAVE_CHECKLIST_SUCCESS';
